# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
name: Create build artifacts
on:
  workflow_dispatch:

jobs:
  build-windows:
   name: Build Windows app
   uses: ./.github/workflows/build-app.yml
   with:
    os: windows-latest
    upload_artifacts: true
  
  build-macos:
   name: Build macOS app
   uses: ./.github/workflows/build-app.yml
   with:
    os: macos-latest
    upload_artifacts: true